### ISSUE TITLE
java.lang.NullPointerException in com.facebook.accountkit.internal.AppEventsLogger.handleResponse

### ISSUE THREAD

**Issue by dnikolaev** [marpies/account-kit-ane#4]
```
java.lang.NullPointerException
	at com.facebook.accountkit.internal.AppEventsLogger.handleResponse(AppEventsLogger.java:526)
	at com.facebook.accountkit.internal.AppEventsLogger.access$600(AppEventsLogger.java:57)
	at com.facebook.accountkit.internal.AppEventsLogger$4.onCompleted(AppEventsLogger.java:510)
	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:188)
	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:42)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dnikolaev** [comment]
Hi @marpies,

Facebook have already fixed this issue according to this [Changelog](https://developers.facebook.com/docs/android/change-log-4x). Please update AccountKit SDK.

**Comment by marpies** [comment]
Hi @dnikolaev,

Yes, I'm in the process of updating AIRFacebook and AccountKit. Update for both will be available tomorrow.

**Comment by marpies** [comment]
Hi @dnikolaev,

The updates have been released. I'll close this issue now. Let me know if you receive reports about this error in the future.
